### ISSUE TITLE
Dependency issues trying out 'test-runner'

### ISSUE THREAD

**Issue by bryphe** [facebookexperimental/reason-native#16]
First off, thanks @kyldvs for working to open source this! Great set of utilities to level up native reason development 💯 

I wanted to try out the test runner in my revery project - I started a PR here: https://github.com/bryphe/revery/pull/78

However, I'm hitting a build error trying to incorporate the new set of dependencies:
```
  "dependencies": {
...
    "@reason-native/test-runner": "*",
    "@reason-native/chalk": "*",
    "@reason-native/file-context-printer": "*"
  },
  "resolutions": {
...
    "@reason-native/test-runner": "facebookexperimental/reason-native:test-runner.json#1b0f213",
    "@reason-native/file-context-printer": "facebookexperimental/reason-native:file-context-printer.json#1b0f213",
    "@reason-native/chalk": "facebookexperimental/reason-native:chalk.json#1b0f213"
  },
```

The build failure is: 
```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @reason-native/chalk@github:facebookexperimental/reason-native:chalk.json#1b0f213
    # esy-build-package: pwd: C:\Users\bryph\.esy\source\i\reason_native__s__chalk--29b06d1810264e9d1ef75895997745b8
    # esy-build-package: running: "refmterr" "dune" "build" "-p" "chalk"
    File "src/chalk/test/lib/dune", line 6, characters 25-40:
    6 |    (libraries  chalk.lib test-runner.lib )
```

@andreypopp mentioned on Discord that a potential fix is to not include tests as part of the release package. Based on our discussion, he said this could be a more general issue that could impact esy w/ monorepos too. One option was to create an esy package per dune lib (dune libs are more granular than esy libs), but that might be heavyweight.

**Comment by kyldvs** [comment]
Hopefully these tools prove useful :)

I also wonder if this will have anything to do with windows. I'll try to take a look - @bandersongit might be able to help as well.

**Comment by bandersongit** [comment]
I think that it is very possible that there are currently problems with the .json files. We've only really played with this within the reason-native repo so far which works as a dune monorepo rather than via esy dependencies/packages. I'll take a look at this today.

**Comment by bryphe** [comment]
> Hopefully these tools prove useful :)

Definitely! I had a half-baked native test runner here: [rejest](https://github.com/bryphe/rejest), but happy to ditch it for this 😉 `Console.log` looks really cool too.

> I also wonder if this will have anything to do with windows. I'll try to take a look - @bandersongit might be able to help as well.

Reproduces on OSX for me as well - I believe it to be a general problem with the dependencies rather than a platform specific issue. 

Thanks for looking into it, @bandersongit ! Keep me posted if you need any more info from me

**Comment by jordwalke** [comment]
The repo is developed as a monorepo. Monorepos allow much more flexibility in how we develop packages at development time like the ability of libraries in package A to depend on libraries in package B and libraries in package B to depend on libraries in package A. There's no circularity between libraries. But there is a circularity between _package_ boundaries that you don't notice because during monorepo development, you're not using packages at all.
Then when publishing the monorepo packages we can cut out those some libraries that would otherwise form a cycle between package (though it is not a cycle between libraries)

If we kept using Dune monorepos, then we'd cut out libraries from "release mode" that cause circularities and properly model package dependencies between .json files. But then we're still not testing a setup that closely resembles production builds because we're using monorepos for development, but packages for releasing.
We're thinking that we want (as much as possible) for dev time environments to resemble release environments. What we saw here was a problem that didn't come up during development of reason-native, but came up in "release mode" because the dev environment was so different. So we wanted to get esy links to be so fast that there's no need for monorepos. The downside being that we can't have circularities like this during development so need to factor something out.

**Comment by bandersongit** [comment]
@bryphe we merged in code to separate out test packages for test-runner and chalk which should solve this dependency. I'm currently in the process of updating the Readme to reflect some updated guidelines as a result.

**Comment by bryphe** [comment]
@bandersongit - nice!

I picked up your change and was able to get tests running. And the failure message is great!
![image](https://user-images.githubusercontent.com/13532591/49332434-ccb75580-f561-11e8-9b02-d9d301422f43.png)

I'll close this out.
