### ISSUE TITLE
[bug] rely is hanging under CI (azure + github actions)

### ISSUE THREAD

**Issue by jaredly** [facebookexperimental/reason-native#223]
I'm testing out using Rely for RLS, and I like lots of things about it! Unfortunately, it's hanging indefinitely under CI :/ See this check run here https://github.com/jaredly/reason-language-server/pull/370/checks?check_run_id=354589981
and here on azure https://jaredly.visualstudio.com/reason-language-server/_build/results?buildId=171&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=6c56d998-158d-5232-283c-5140104799fc

**Comment by kyldvs** [comment]
Does it work okay locally for you?

I wonder if it's related to the differences in your dune file, we normally use the [link-all flag](https://github.com/facebookexperimental/reason-native/blob/master/tests/dune#L5) but it looks like you are [including each set of tests manually](https://github.com/jaredly/reason-language-server/blob/rely/test/RunTests.re#L1-L3)

**Comment by jaredly** [comment]
Yup it runs just fine locally

**Comment by jaredly** [comment]
Ok so this is fun, I made a change to `print_endline` at the beginning of the `RunTests.re` main file, and ... somehow execution hangs before we even get to that.

**Comment by kyldvs** [comment]
Is there a reason for copying the exe to a new location before running it?

https://github.com/jaredly/reason-language-server/blob/rely/.ci/build-platform.yml#L23

What happens if you move the running of the exe into a simple script call like:

- https://github.com/facebookexperimental/reason-native/blob/master/.ci/esy-build-steps.yml#L31
- https://github.com/facebookexperimental/reason-native/blob/master/scripts/test-ci.cmd

Perhaps also test if you can get an `echo` from the bash script to work?

(you can ignore all the .cmd suffixes and `:;` comments probably I think we do that for windows)

**Comment by kyldvs** [comment]
Also I'm not familiar with `.yml` syntax but is it possible that the [cp](https://github.com/jaredly/reason-language-server/blob/rely/.ci/build-platform.yml#L23-L24) command is being called with 3 args once rather than this being 2 commands?

What if you change it to `cp $(esy x which RunTests.exe) RunTests.exe && ./RunTests.exe`

**Comment by jaredly** [comment]
looks like the error must have been on my end
